sudo: required
services:
  - docker

before_install:
  - docker build -t guillepowermetal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run guillepowermetal/react-test npm test -- --coverage

after_success:
  - docker build -t guillepowermetal/multi-nginx ./nginx
  - docker build -t guillepowermetal/multi-server ./server
  - docker build -t guillepowermetal/multi-worker ./worker
  - docker build -t guillepowermetal/multi-client ./client
# log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push images to docker hub
  - docker push guillepowermetal/multi-client
  - docker push guillepowermetal/multi-nginx
  - docker push guillepowermetal/multi-server
  - docker push guillepowermetal/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-568821911544
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY